"""Added user_name to attendance

Revision ID: efb1c0260a11
Revises: eba4c8d907a3
Create Date: 2025-05-14 10:46:12.319929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efb1c0260a11'
down_revision = 'eba4c8d907a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=80), nullable=True))
        batch_op.drop_constraint('attendance_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('attendance_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
